### PR TITLE
Aruba workbook

### PR DESCRIPTION
**Pull request by Joe-Neville**
- Master README.md updated
- ARUBA1 workbook added

### CODE REVIEW

**Review by Didier-Lalli — COMMENTED** [review]
Thanks for your submission Joe. Could you change workbook with notebook. 
Also I don't understand the dependencies section. It says Bash then mentions python request. So I suspect it might be a cut/paste problem.

**Comment by Joe-Neville** [comment]
I've changed the name of the PR.
The dependencies line about bash is copied from your API101 README. Shall I remove that?
The Aruba workbook needs 'requests' for the API calls, hence why it is mentioned.

**Comment by Didier-Lalli** [comment]
If your notebook uses python, replace bash with python and add your module. Yes.

**Comment by Joe-Neville** [comment]
Ok, 'workbook' replaced with 'notebook' and requirements updated.

**Review by Didier-Lalli — APPROVED** [review]
Looks good.

**Comment by Didier-Lalli** [comment]
It’s up! Thanks

How did you find the process?

**Pull request merged**
